export const MANAGER_ATLAS_FAQS = [
  { question: "What is Manager Return Atlas?", answer: "A historical football research tool. Follow a manager across clubs, compare meetings with another manager and see what a constant stake on their team, the draw or their opponent would have returned at the recorded prices." },
  { question: "How do I compare two managers?", answer: "Enter a manager, then an opposing manager. The tool keeps only their meetings in the archive, including meetings at different clubs. Leave the opponent blank for the manager’s full included record. You can narrow the selection by league, season, venue and the team’s win odds." },
  { question: "What do ROI and units mean?", answer: "Each included bet risks one unit: one equal-sized stake. If your unit is £10, +5u means £50 profit. ROI is profit divided by everything staked. Ten £10 bets risk £100 in total; £12 profit is +12% ROI. The tool uses the actual recorded odds, not just the number of wins." },
  { question: "Does backing the opponent win when the match is drawn?", answer: "No. These are three separate match-winner bets: the manager’s team, the draw, or the opposing team. A draw loses either team-win bet. Double chance, draw no bet and Asian handicaps need their own recorded prices and are not substituted here." },
  { question: "How are expected wins calculated?", answer: "The team, draw and opponent odds are converted into probabilities and adjusted together to remove the bookmaker’s margin. If a team has a 40% chance, that match contributes 0.40 expected wins. Add these across ten similar matches and the expectation is four wins. Winning six would be two above expectation. This is different from ROI and does not prove the manager caused the difference." },
  { question: "Which competitions and dates are covered?", answer: "Included domestic league fixtures from the Premier League, Serie A, La Liga, Bundesliga and Ligue 1, starting in 2012/13. The latest included match date is shown at the top. Cups and European competitions are excluded. Coverage varies: this is not every manager’s complete career, and records with unresolved managers, results or prices are left out." },
  { question: "How often does the manager archive update?", answer: "A weekly cloud job runs after Football Return Atlas on Tuesdays. It checks new results, recorded pre-match prices and the manager assigned to each match before publication. A failed check keeps the last good archive. Manager activity and identity reviews are also scheduled monthly. The latest match date can be earlier than the update date." },
  { question: "Are small head-to-head samples hidden?", answer: "No. Even one meeting remains available, with a small-sample label. Two or three wins can produce a striking ROI without establishing a repeatable advantage. Open the match ledger, check the odds and sample size, and treat historical returns as research rather than a forecast." },
];
