import type { ResourceGuide } from "./resource-guides";

export const ODDS_VALUE_GUIDE: ResourceGuide = {
  title: "From odds to value: four checks before a bet",
  description: "A practical betting walkthrough: read the probability, remove the margin, compare the available price and test the stake. Simple examples with free tools at each step.",
  takeaway: "A likely winner and a good bet are different questions. Start with the price, make your probability assumption explicit and check how much being wrong could cost.",
  icon: "method", published: "2026-09-24", minutes: 6,
  sections: [
    { id: "probability", title: "Read what the odds require", paragraphs: ["Decimal odds tell you the total return, including your stake. A £10 bet at 2.50 returns £25 if it wins: £15 profit plus your £10 back. The break-even probability is one divided by the decimal price.", "At 2.50 you need to win 40% of comparable bets to break even, before any other costs. This is a requirement implied by the price, not proof that the selection has a 40% chance."], example: { title: "The same selection at two prices", figures: [["Price 2.50 · break-even", "40.0%"], ["Price 2.00 · break-even", "50.0%"]], explanation: "Shorter odds demand a higher win rate. A good selection can become a poor bet when the price drops." }, links: [["Try the odds inputs", "/calculator?tool=margin"]] },
    { id: "margin", title: "Remove the bookmaker’s margin", paragraphs: ["Read every possible outcome in the same market. If both sides of a two-way market are 1.90, each implies 52.63%. Together they total 105.26%, an overround of 5.26 percentage points.", "Proportional removal divides each implied probability by their total. Here that produces 50% per side, or fair odds of 2.00. The symmetric example is easy; on uneven prices, different removal methods can produce meaningfully different estimates."], example: { title: "A two-way market at 1.90 / 1.90", icon: "compare", figures: [["Implied probabilities combined", "105.26%"], ["Fair odds after proportional removal", "2.00 / 2.00"]], explanation: "The 5.26% overround is not the bookmaker’s guaranteed profit on turnover. Under a balanced-book assumption, the equivalent theoretical hold is 5.00%. Actual profit depends on the stakes and results." }, note: "Use prices from the same market and timestamp. Combining the best prices across several bookmakers is a different exercise. A margin-adjusted reference is still an estimate, not the true probability revealed.", links: [["Compare margin-removal methods", "/calculator?tool=margin"], ["Compare bookmaker margins", "/bookmakers"]] },
    { id: "value", title: "Compare the odds you can actually take", paragraphs: ["For a bet with only win and loss outcomes, expected value per pound is probability × decimal odds − 1. Suppose your estimated chance is 50% and another bookmaker offers 2.10. The calculation is 0.50 × 2.10 − 1 = +5%.", "That does not mean a £10 bet pays you 50p today. It wins £11 or loses £10. The 50p is the average net result implied by the assumed probability over repeated comparable bets. If the probability estimate is wrong, the supposed edge can disappear."], example: { title: "How price movement changes the same idea", figures: [["50% estimate at odds of 2.10", "+5% EV"], ["50% estimate at odds of 1.95", "−2.5% EV"]], explanation: "At a 50% estimate, 2.00 is the break-even price. To require 3% expected value, you would need at least 1.03 ÷ 0.50 = 2.06. That threshold depends on the estimate being credible." }, note: "Football draw-no-bet has a third settlement: a refund. Use probability of a win × (odds − 1) − probability of a loss. The refunded draw contributes zero. Do not use the win/loss-only formula without accounting for that refund.", links: [["Check EV against a fair reference", "/calculator?tool=margin"], ["Calculate football DNB and double chance", "/calculator/football"]] },
    { id: "stake", title: "Size the risk, including estimation error", paragraphs: ["Only size a stake after judging the price. Full Kelly uses the estimated probability and odds to maximise long-run logarithmic growth under its assumptions. It can be too aggressive when the probability is uncertain or several bets share the same risk.", "With a £1,000 bank, a 50% estimate and odds of 2.10, full Kelly is about £45.45. Quarter Kelly is about £11.36. Those are outputs of the example, not recommended stakes for everyone. At a true win probability of 47%, the bet has negative expected value despite the original 50% estimate."], example: { title: "A £1,000 hypothetical bank", icon: "bankroll", figures: [["Full Kelly at 50% / 2.10", "£45.45"], ["Quarter Kelly, same assumptions", "£11.36"]], explanation: "Reducing the stake reduces exposure; it cannot turn a bad probability estimate into an edge. Use the estimate-error slider to see the consequences." }, links: [["Test Kelly and estimate error", "/calculator?tool=kelly"], ["Read the full Kelly guide", "/resources/kelly-criterion-sports-betting"]] },
    { id: "evidence", title: "Keep the evidence after the bet", paragraphs: ["Record the selection, market, line, obtainable odds, stake and publication time before the event. Keep losing and void bets alongside winners. Profit, sample size and drawdown belong together.", "Return Atlas is useful for exploring historical patterns. Finding a profitable club or player after trying many filters does not establish a future edge. Keep any hypothesis separate from a test on later matches, and distinguish hypothetical flat-stake returns from our published selections."], links: [["Read a track record properly", "/resources/how-to-read-a-tipster-track-record"], ["Explore all betting tools", "/tools"], ["View our published record", "/track-record"]] },
  ],
};
