import type { EditorialIconName } from "@/components/EditorialIcon";

export type GuideSection = {
  id: string; title: string; paragraphs?: string[];
  diagram?: "drawdown" | "kelly";
  example?: { title: string; icon?: EditorialIconName; figures: [string, string][]; explanation: string };
  table?: { caption: string; headings: string[]; rows: string[][] };
  steps?: [string, string][]; note?: string; links?: [string, string][];
};
export type ResourceGuide = { title: string; description: string; takeaway: string; icon: EditorialIconName; published: string; minutes: number; sections: GuideSection[] };
export const GUIDE_REVIEW_DATE = "2026-09-23";
export const RESOURCE_GUIDES: Record<string, ResourceGuide> = {
  "how-to-read-a-tipster-track-record": {
    title: "How to verify a tipster track record",
    description: "A winning screenshot tells you very little. Here is how to check the complete record, recalculate the returns and find out whether the quoted prices were available.",
    takeaway: "Ask for the full bet list before judging the headline ROI. Publication timing, obtainable odds and all losing bets matter as much as the profit figure.",
    icon: "guide", published: "2026-05-13", minutes: 7,
    sections: [
      { id: "timestamps", title: "Could you have followed the bets?", paragraphs: ["Start with a practical question: what could a follower actually have placed before the event? Each selection should identify the fixture, market, line, odds, bookmaker, stake and publication time. A player name with a winning slip attached afterwards is not enough.", "A timestamp printed on a website can be edited. Stronger evidence comes from an independently recorded pre-event post, a third-party proofing service, or an audit trail that retains changes. A public ledger is useful, but public and independently verified are different claims."], steps: [["Pick five past selections", "Include winners and losers from different dates. Locate their original pre-event posts, not just the settled results."], ["Compare the details", "Check the published line, odds and stake against the ledger. Corrections should be visible and explained."], ["Check price availability", "A briefly available maximum price or a restricted promotional boost may not represent what most followers could obtain."]] },
      { id: "losses", title: "Recalculate profit and ROI yourself", paragraphs: ["ROI here means profit divided by total amount staked. It is not the percentage growth of a starting bank. At decimal odds, a winning £10 bet at 2.50 returns £25 in total: £15 profit plus the £10 stake. A losing £10 bet loses £10.", "Read the settlement rules. Voids, half-wins, half-losses, dead heats and cash-outs can change both profit and the turnover denominator. Use the same treatment as the published record, and ask for clarification where it is missing."], example: { title: "A profitable month, with all its losses included", figures: [["Total staked", "£1,000"], ["Total returned", "£1,080"], ["Net profit", "+£80"], ["ROI", "+8%"]], explanation: "For 100 bets at £10, 40 winners at 2.70 and 60 losers return £1,080. The win rate is only 40%, but ROI is +8%. Neither win rate nor a collection of winning slips explains the record on its own." }, table: { caption: "Three figures that answer different questions", headings: ["Measure", "Calculation", "What it tells you"], rows: [["Profit", "Returns − stakes", "Money or units won after losses"], ["ROI", "Profit ÷ turnover × 100", "Return on the amount repeatedly staked"], ["Bank growth", "Profit ÷ starting bank × 100", "Change relative to an initial bankroll"]] }, note: "In this example a £500 starting bank grows by 16%, while ROI remains 8%. Calling both figures ROI would double the apparent performance." },
      { id: "sample-size", title: "Look beyond the best month", paragraphs: ["There is no magic number of bets that proves skill. A record of 500 short-priced bets behaves differently from 500 longshots. Several bets on the same player or match are also related, so the count can overstate how many independent opportunities were tested.", "Look at the complete timeline, then separate sports, markets and odds ranges. Ask whether a profitable total depends on a single unusually large winner. Compare the stated variable-stake record with a level-stake version: both can be valid, but they answer different questions.", "Historical simulations should be labelled separately from tips published in advance. A strategy selected because it looked best among hundreds of backtests needs new, unseen results before its performance is persuasive."], steps: [["Include every month", "A rolling last-30-days graphic is useful only if the older results remain accessible."], ["Include every selection", "Do not let losing markets disappear from the headline after they stop being promoted."], ["Account for costs", "Subtract subscription charges, relevant commission and any consistent difference between published and obtainable odds."]] },
      { id: "clv-and-drawdown", diagram: "drawdown", title: "Check the price quality and the rough stretches", paragraphs: ["Closing-line value compares the taken price with a specified market shortly before the start. Repeatedly beating a credible, margin-adjusted close is useful evidence about pricing. It cannot certify a tipster by itself: the benchmark may be weak, timestamps may be wrong, and the tracked subset may exclude awkward bets.", "Drawdown is the fall from a previous bankroll peak to a later low. It answers a question the final profit does not: how much money would a follower have seen disappear along the way? Ask whether the graph uses the actual sequence of settled bets or a simulation."], example: { title: "Still up overall, but down from the peak", figures: [["Starting bank", "£1,000"], ["Peak bank", "£1,200"], ["Later low", "£900"], ["Peak drawdown", "25%"]], explanation: "The fall is £300 from the £1,200 peak, or 25%. A later recovery does not erase that experience. A final balance alone would hide it." }, links: [["Understand CLV", "/resources/closing-line-value"], ["Inspect our public record", "/track-record"]] },
      { id: "before-you-follow", title: "A five-minute decision checklist", steps: [["Can I inspect the original tips?", "Prefer an auditable history over unverified screenshots or a badge with no explanation."], ["Can I reproduce the headline?", "The stakes, settlement rules and turnover should produce the stated profit and ROI."], ["Can I obtain comparable prices?", "Check your own bookmakers, limits and the time between publication and your bet."], ["Can I see the full risk?", "Read losing months, drawdown, market splits and the number of bets behind each claim."], ["What remains unverified?", "Treat missing information as missing. Do not replace it with an assumption that the service is either brilliant or dishonest."]], note: "A good historical record supports a judgement about past performance. It does not promise your next month will be profitable." },
    ],
  },
  "closing-line-value": {
    title: "Closing line value: did you get a good price?",
    description: "Your bet can lose even when you took a useful price. Learn what CLV measures, how to remove the closing margin and when a comparison is misleading.",
    takeaway: "Compare the same selection and settlement rules before the start. Beating the displayed closing odds is a price improvement; beating a fair closing price is the stronger benchmark.",
    icon: "markets", published: "2026-02-12", minutes: 7,
    sections: [
      { id: "introduction", title: "The everyday idea", paragraphs: ["Imagine buying the same train ticket for £20 before its price rises to £25. You secured a better deal than someone buying later. CLV asks a similar question about a bet: did you take better odds than the final comparable price before the event? The difference is that neither price tells you whether the bet will win.", "For a back bet, larger decimal odds pay more for the same winning outcome. Taking 2.10 before the identical market closes at 1.95 is a positive raw price comparison. Taking 1.80 before it closes at 2.00 is negative."] },
      { id: "what-is-clv", title: "One bet, three prices", example: { title: "A tennis match-winner bet", icon: "markets", figures: [["Price you took", "2.10"], ["Displayed close", "1.95"], ["Other player’s close", "1.95"], ["Fair closing price", "2.00"]], explanation: "The two closing prices imply a combined 102.56% probability. Proportionally removing that margin leaves each player at 50%, or fair odds of 2.00. Your 2.10 is 5% above that fair close, rather than the 7.69% improvement over the displayed 1.95." }, note: "This example assumes a two-outcome market with identical retirement and settlement rules. The margin-removal method is part of the comparison, not a hidden detail." },
      { id: "calculate", title: "Calculate it without mixing up percentages", table: { caption: "The same example, measured three ways", headings: ["Measure", "Working", "Result"], rows: [["Raw price improvement", "(2.10 ÷ 1.95 − 1) × 100", "+7.69%"], ["Fair-close CLV", "(2.10 ÷ 2.00 − 1) × 100", "+5.00%"], ["Raw probability difference", "(1 ÷ 1.95 − 1 ÷ 2.10) × 100", "+3.66 percentage points"]] }, paragraphs: ["These figures are different definitions, not conflicting answers. Label which one you use. For a fair-close calculation, first collect every mutually exclusive outcome in the closing market, remove the margin, then compare your taken odds with the resulting fair price.", "For proportional removal, divide each implied probability by their total. If the selected outcome has closing probability p after that adjustment, fair odds are 1/p and fair-close CLV is (taken odds × p − 1) × 100. Other de-vig methods can give different estimates, especially on uneven markets."], links: [["Try the Closing line calculator", "/calculator?tool=clv"]] },
      { id: "why-clv", title: "What it can tell you—and what it cannot", paragraphs: ["A well-traded closing market has had time to react to news and betting activity. That makes it a useful comparison point. It is still a market estimate, not the true probability written down somewhere.", "Repeated positive fair-close CLV can support the case that your process finds useful prices. It does not guarantee profit, prove a model is calibrated, or tell you how much to stake. Small samples, correlated bets, low limits and weak reference markets all reduce the strength of the evidence.", "A winning bet can have negative CLV; a losing bet can have positive CLV. Record both facts. Do not call every profitable bettor lucky, or every bettor beating the close skilled, from one short run."] },
      { id: "beat-closing", title: "The price changed before you could place it", example: { title: "The tip’s CLV is not necessarily yours", figures: [["Published odds", "2.10"], ["Your taken odds", "1.90"], ["Fair close", "2.00"], ["Your fair-close CLV", "−5%"]], explanation: "The published price beats the fair close by 5%, but your actual 1.90 is 5% below it. Track your receipt, not the price in a tip you saw earlier. A result cannot recover the opportunity to place a better price." }, paragraphs: ["Do not rush into any early price simply to beat a future number. Early markets may offer smaller limits, wider margins or incomplete team news. Decide whether the currently available price still meets your assessment."] },
      { id: "tracking", title: "A repeatable tracking routine", steps: [["Save the bet at placement", "Selection, line, bookmaker, taken odds, stake and timestamp. Keep free bets and boosts separate."], ["Choose the close in advance", "Use a consistent reference and cut-off before the start. Record the actual capture time and all sides needed to remove margin."], ["Match the contract", "Use the same handicap, total, player threshold and settlement rules. Mark missing or mismatched records rather than forcing a comparison."], ["Review coverage as well as CLV", "Show how many bets have a usable close. Label equal-bet and stake-weighted averages separately; neither is automatically the realised ROI."]] },
      { id: "mistakes", title: "When you should leave the CLV blank", paragraphs: ["Over 2.5 shots and over 3.5 shots are different bets. If the threshold moved, comparing their decimal prices directly is meaningless. Keep a closing quote for the original line, or record the line movement separately.", "Likewise, an in-play capture is not a pre-match close. A stale quote from hours earlier is a last observed price; label it that way. If the opposing side is unavailable, you can still show raw price movement, but you cannot reconstruct a full two-way fair close from one price alone."] },
      { id: "practice", title: "Use it alongside results", paragraphs: ["For player props, confirm the player, threshold and rules for participation. For tennis, check how each bookmaker settles retirements and walkovers. Apparently better odds may cover a different contract.", "If ROI and CLV diverge for a long period, investigate the timestamps, market quality, settlement and selection process. Do not automatically explain everything as bad luck."], links: [["Verify a tipster record", "/resources/how-to-read-a-tipster-track-record"]] },
      { id: "conclusion", title: "Your next step", paragraphs: ["Take a small batch of your recent bets and compare the actual taken prices with a consistent close. Write down the definition and missing-data count. That gives you a useful starting point without pretending the metric can predict the next result."] },
    ],
  },
  "kelly-criterion-sports-betting": {
    title: "Kelly criterion: stake sizing without false certainty",
    description: "A worked £1,000 example, a smaller-stake comparison and the question that matters most: what happens when your estimated win probability is wrong?",
    takeaway: "Kelly converts an estimated edge into a fraction of a bankroll. It cannot create an edge, and an overconfident probability can turn its suggested stake into an overbet.",
    icon: "bankroll", published: "2026-02-12", minutes: 7,
    sections: [
      { id: "introduction", title: "What question does Kelly answer?", paragraphs: ["Suppose you believe a bet is good value. The next question is how much of a dedicated betting bank to risk. Too little produces slower growth when the edge is real. Too much makes losses disproportionately damaging.", "The Kelly criterion chooses the fraction that maximises expected logarithmic bankroll growth under its assumptions. That is a long-run mathematical objective, not a target for next month’s profit or a guarantee against severe drawdowns.", "The starting bank in these examples is money separately set aside for betting, not savings needed for bills. The figures illustrate the arithmetic; they are not a recommendation to bet that amount."] },
      { id: "mathematics", diagram: "kelly", title: "The formula, in ordinary numbers", paragraphs: ["For a simple win-or-lose bet: full Kelly fraction = (decimal odds × win probability − 1) ÷ (decimal odds − 1). Use probability as a decimal: 55% becomes 0.55. If the result is zero or negative, this back-bet calculation calls for no stake.", "The formula assumes the stated payout, a probability you can rely on, and losses limited to the stake. Bets with pushes, commissions or different settlement outcomes need those features incorporated; do not silently apply the two-outcome formula to them."], example: { title: "£1,000 bank, odds of 2.00, estimated chance of 55%", icon: "bankroll", figures: [["Estimated EV", "+10%"], ["Full Kelly", "10% · £100"], ["Half Kelly", "5% · £50"], ["Quarter Kelly", "2.5% · £25"]], explanation: "(2.00 × 0.55 − 1) ÷ (2.00 − 1) = 0.10. A quarter of that fraction is 0.025. Multiply by the current £1,000 bank to get £25. The +10% expected value is conditional on the 55% estimate being correct." } },
      { id: "limitations", title: "The fragile input is your probability", table: { caption: "Same odds of 2.00, different true chances", headings: ["Actual chance", "Actual EV", "Full Kelly if known"], rows: [["55%", "+10%", "10% of bank"], ["52%", "+4%", "4% of bank"], ["50%", "0%", "No positive stake"], ["48%", "−4%", "No back bet"]] }, paragraphs: ["If you size at 55% but the true chance is 52%, the original 10% stake is 2.5 times the full Kelly fraction justified by that true chance. At these numbers it has negative expected log growth, even though the bet itself still has positive expected value.", "If the real chance is 48%, reducing the stake does not make the bet profitable. Fractional Kelly reduces exposure to estimation error; it does not repair a wrong forecast."], note: "A 4% fall in bankroll needs a 4.17% gain to recover. A 50% fall needs a 100% gain. This asymmetry is why stake size matters even when average returns look attractive." },
      { id: "fractional", title: "Why people use fractions of Kelly", paragraphs: ["Half, quarter and one-tenth Kelly multiply the calculated fraction by 0.5, 0.25 and 0.1. Smaller fractions generally trade some growth potential for smaller swings when the assumed edge is correct. They can still lose money and suffer long drawdowns.", "There is no universal fraction that becomes safe just because the market is tennis or player props. Probability uncertainty, long odds, liquidity, simultaneous bets and your ability to tolerate losses all matter. Treat calculator presets as scenarios, not rules you must follow."], steps: [["Start with a credible estimate", "A personal hunch written as 60% is still a hunch. Test probability calibration before treating the number as stake-sizing evidence."], ["Apply a fraction and an exposure limit", "Consider money already at risk in other bets. A series of individually modest stakes can add up to substantial exposure."], ["Recalculate from the current bank", "After a loss the same percentage means a smaller cash stake. Do not increase it to chase the previous balance."]] },
      { id: "practice", title: "Three bets can share one underlying risk", paragraphs: ["A striker to score, have two shots on target and take a penalty are not independent opportunities. Minutes, injury and the same match events can affect all three. Applying a full standalone Kelly stake to each does not account for that relationship.", "The same problem arises with several bets on one tennis match. A proper portfolio calculation needs the joint outcome probabilities. A simple single-bet calculator does not provide that. Keep total exposure visible rather than adding every suggested stake together."] },
      { id: "implementation", title: "Try an error test before a stake test", steps: [["Enter the actual odds", "Use what you can place now, not a price that disappeared when the tip was published."], ["Enter an estimated probability", "Be explicit about where the estimate comes from and its uncertainty."], ["Move the estimate-error slider", "In our calculator, the stake stays based on your belief while the simulated outcomes use a lower probability. See how the picture changes."], ["Read the drawdowns", "The median finish is only one summary. Read the losing scenarios and risk of the bank being halved too."]], links: [["Try the Kelly calculator", "/calculator?tool=kelly"], ["Read our methodology", "/the-edge"]] },
      { id: "comparison", title: "Kelly versus a simpler stake", table: { caption: "Choose a method you can explain", headings: ["Approach", "What it does", "Main limitation"], rows: [["Fixed cash stake", "Same cash amount per bet", "Becomes a larger share of a shrinking bank"], ["Fixed percentage", "Cash stake follows the current bank", "Does not distinguish stronger and weaker edges"], ["Fractional Kelly", "Uses odds and estimated probability", "Sensitive to a wrong probability and correlated bets"]] }, paragraphs: ["Without credible probabilities, a Kelly output is false precision. A small, predefined staking budget can be easier to monitor, although no staking plan turns negative-value bets into positive-value ones. Doubling after losses escalates exposure; it does not change the underlying price."] },
      { id: "conclusion", title: "Where the idea comes from", paragraphs: ["J. L. Kelly’s 1956 paper linked information to the growth rate of capital. The useful lesson for a bettor is to treat stake size and probability quality together. A sophisticated fraction cannot compensate for an untested input."], links: [["Read Kelly’s original paper", "https://doi.org/10.1002/j.1538-7305.1956.tb03809.x"]] },
    ],
  },
  "fair-odds-lab-explained": {
    title: "Fair odds and value: what does the price tell you?",
    description: "Turn a probability into a price, remove a bookmaker’s margin and see why the same selection can be worth considering at one price and poor value at another.",
    takeaway: "A likely winner is not automatically a good bet. Compare the payout with the probability, then question how reliable that probability is.",
    icon: "compare", published: "2026-05-13", minutes: 5,
    sections: [
      { id: "fair-price", title: "Think of a fair coin", paragraphs: ["A fair coin has a 50% chance of landing heads. Decimal odds of 2.00 return £20 from a winning £10 stake. At those odds, repeated independent £10 bets have zero expected profit before any costs: half win £10, half lose £10.", "At 1.80 the same winning bet earns only £8, while a loss still costs £10. At 2.20 a win earns £12. The event has not changed; the price has. That is the basic distinction between predicting a winner and finding value.", "Fair odds = 1 ÷ probability. A 25% estimated scoring chance corresponds to 4.00; 40% corresponds to 2.50. The word estimated matters: a model’s fair price is conditional on its inputs, not a fact about the future."], example: { title: "The same 50% chance at three prices", figures: [["Odds 1.80", "−£1 expected / £10"], ["Odds 2.00", "£0 expected / £10"], ["Odds 2.20", "+£1 expected / £10"]], explanation: "Expected profit averages across hypothetical repetitions. Your next £10 bet still either wins its payout or loses £10. You do not receive £1 every time." } },
      { id: "reference-price", title: "Why a bookmaker’s probabilities add up above 100%", paragraphs: ["Take a two-player market priced at 1.90 on both sides. Each implies 52.63%, so together they add to 105.26%. The extra 5.26 percentage points are the overround. They are not a prediction that both players can win.", "Proportional margin removal divides each implied probability by the total. Here that restores 50% per player, or fair odds of 2.00. Shin and odds-ratio methods allocate the adjustment differently on uneven markets. They are alternative estimates, not ways to uncover a guaranteed true price.", "Use a complete, mutually exclusive market. You cannot remove the margin from a list of anytime goalscorers by normalising their probabilities: several players can score in the same match."], links: [["Compare de-vig methods", "/calculator?tool=margin"]] },
      { id: "price-gap", title: "Probability gap and expected value are different", example: { title: "A goalscorer you estimate at 40%", figures: [["Model fair odds", "2.50"], ["Available odds", "2.80"], ["Raw implied chance", "35.71%"], ["Estimated EV", "+12%"]], explanation: "The probability gap is 40% − 35.71% = 4.29 percentage points. Expected value is 2.80 × 0.40 − 1 = 12%. These are different measurements. For £10, +12% means £1.20 expected profit under the estimate, not a promised return." }, paragraphs: ["If the price falls to 2.30, the same 40% estimate gives −8% EV. If the player is benched and the estimate drops to 30%, even 2.80 gives −16% EV. A good-looking price gap is a reason to check minutes, team news and the market mapping."] },
      { id: "what-it-is-not", title: "How to use the Fair Odds Lab", steps: [["Check the fixture and update time", "A recorded reference price may have moved. Missing data means there is no comparison, not that the model has found no value."], ["Read the player assumptions", "Likely minutes, starting status and penalty responsibility can all change a goalscorer estimate."], ["Compare your actual price", "Use the exact market and bookmaker rules. The board’s reference is not a promise of the best available odds."], ["Keep research and published tips distinct", "A model disagreement is research. Latest hits show recent successful examples, not every signal or an audited profit record."]], links: [["Open Fair Odds Lab", "/fair-odds-lab"], ["View published results", "/track-record"]] },
    ],
  },
  "clay-season-tennis-model-caveats": {
    title: "Clay-court tennis betting: make the surface count",
    description: "A useful clay assessment starts with the right comparison. Separate surface form, sample size and price instead of assuming a player’s recent wins transfer unchanged.",
    takeaway: "Surface-specific results add context. They do not automatically establish an edge, and a handful of clay wins should not outweigh the quality of the opposition or the current price.",
    icon: "analysis", published: "2026-05-13", minutes: 5,
    sections: [
      { id: "why-clay-is-different", title: "Recent form needs a surface label", paragraphs: ["A player’s last ten matches may mostly come from hard courts, indoors, or against weaker opposition. That record answers a different question from how the player is likely to perform in the next clay event.", "Look at the player’s serve and return performance on the relevant surface, the opponents faced and the age of the sample. Tournament conditions can differ within the same surface label too. Avoid treating every clay venue as interchangeable."], example: { title: "Eight wins out of ten can hide the comparison you need", figures: [["Last 10 overall", "8 wins"], ["Hard-court matches", "8"], ["Clay matches", "2"], ["Clay sample", "Too small alone"]], explanation: "The headline 80% win rate is accurate, but it is not an estimate of the next clay match’s win probability. You still need a broader surface history, opponent context and a price." } },
      { id: "what-we-watch", title: "Four questions before looking at the odds", steps: [["Who were the opponents?", "Winning lower-level matches is different from beating established tour players. Compare like with like where possible."], ["How recent and how large is the sample?", "Several seasons give more matches but can mix different stages of a player’s career. A recent-only view can be noisy."], ["What is known about preparation?", "Recent match load, retirements and publicly reported fitness issues deserve attention. Do not diagnose an injury from a losing score."], ["Which market are you pricing?", "A match winner, games handicap and total games require different outcome estimates."]] },
      { id: "model-response", title: "A winning pick can still lose the handicap", example: { title: "The score matters for games markets", figures: [["Match result", "7–6, 7–6"], ["Match winner", "Wins"], ["Games difference", "+2"], ["−3.5 games bet", "Loses"]], explanation: "The favourite wins in straight sets but only takes two more games than the opponent. A strong match-win probability does not tell you the probability of covering −3.5 games." }, paragraphs: ["Probability calibration means checking whether groups of predictions behave roughly as forecast. In a hypothetical set of 100 independent matches each assigned 60%, about 60 wins are expected, with natural variation. One batch returning 54 wins does not prove the model is broken; repeated misses across unseen samples deserve investigation.", "Increasing an edge threshold is one response to uncertainty, but it is not evidence that the remaining bets will be profitable. A change should be evaluated on results not used to choose it."] },
      { id: "where-it-goes-next", title: "Use the tools to ask a narrower question", paragraphs: ["In Return Atlas, choose a player, clay and a defined period, then compare backing the player with backing the opponent. Read the match count and the included date range alongside ROI. A profitable historical favourite split is a description of that sample, not a forecast for the next match.", "Keep any rule you discover separate from a test on later matches. Searching dozens of players and filters will inevitably produce attractive historical pockets, even without a repeatable edge."], links: [["Explore Return Atlas", "/return-atlas"], ["View tennis selections", "/tennis-tips"]] },
    ],
  },
};
