/** UK online match-winner rules, reviewed against the linked primary sources. */
export const RETIREMENT_REVIEW_DATE = "2026-10-07";
export type RetirementRuleFamily = "match" | "set" | "protection" | "point";
export type RetirementRule = {
  name: string; family: RetirementRuleFamily; threshold: string;
  early: string; own: string; opponent: string; note: string;
  detail: string; source: string; sourceLabel?: string; extraSource?: string;
};
export const RETIREMENT_FAMILIES: Record<RetirementRuleFamily, string> = {
  match: "Completed match", set: "Completed first set", protection: "First set + refund", point: "First point",
};
const protectedTour = "ATP, WTA, Grand Slams, Challenger, Davis Cup and Billie Jean King Cup. ITF, UTR and exhibition retirements void both players’ match bets at any stage.";
export const TENNIS_RETIREMENT_RULES: RetirementRule[] = [
  { name: "bet365", family: "match", threshold: "Match must finish", early: "Both bets refunded", own: "Refund", opponent: "Refund under standard rules", note: "A separate retirement promotion can award Bet Credits when your opponent retires. This is not the same as a cash win.", detail: "Standard Match Betting rules include bets placed during play. A disqualification is different: the player awarded the match is the winner. The retirement promotion covers bets placed before play on singles Match Winner in ATP, WTA and Grand Slam events. Challenger, World Tennis Tour and UTR are excluded. If your player retires, the bet is void; eligible opponent retirements receive Bet Credits on singles, while the leg is treated as a winner in multiples. Check the promotion’s full conditions.", source: "https://help.bet365.com/s/en-gb/sportsrules/tennis", extraSource: "https://help.bet365.com/s/en-gb/sports/tennis-retirement" },
  { name: "Sky Bet", family: "protection", threshold: "First set must finish", early: "Both bets refunded", own: "Refund", opponent: "Paid as a winner", note: protectedTour, detail: "The first set must be completed, whoever wins it. Sky’s retirement table and separate disqualification wording are not identical: confirm an early disqualification directly with Sky. This row describes retirement, not a disqualification. Check the exact market rules for any bet placed during play.", source: "https://support.skybet.com/app/answers/detail/tennis-rules/" },
  { name: "Paddy Power", family: "protection", threshold: "First set must finish", early: "Both bets refunded", own: "Refund", opponent: "Paid as a winner", note: protectedTour, detail: "The rules give the same tournament conditions for retirement and disqualification. A walkover voids the match bet. These are the online Match Betting conditions; check the bet’s market information for any specific in play terms.", source: "https://helpcenter.paddypower.com/app/answers/detail/tennis-rules/" },
  { name: "Betfair Sportsbook", family: "protection", threshold: "First set must finish", early: "Both bets refunded", own: "Refund", opponent: "Paid as a winner", note: protectedTour, detail: "This entry is for Betfair Sportsbook only. It must not be applied to Betfair Exchange. The Sportsbook rules apply these tournament conditions to retirement and disqualification; a walkover voids the match bet. Check any specific in play terms shown with the market.", source: "https://support.betfair.com/app/answers/detail/tennis-rules/" },
  { name: "Ladbrokes", family: "set", threshold: "First set must finish", early: "Both bets refunded", own: "Loses", opponent: "Paid as a winner", note: "Once the first set is complete, the player advancing or awarded the match is the winner. The retiring player’s bet loses.", detail: "The same first set threshold applies to a disqualification. The published Match Winner clause does not give a separate retirement threshold for bets placed during play. Check any specific terms displayed with your bet.", source: "https://help.ladbrokes.com/en/sports-help/rules/tennis" },
  { name: "Coral", family: "set", threshold: "First set must finish", early: "Both bets refunded", own: "Loses", opponent: "Paid as a winner", note: "The first set must be complete. After that, the player advancing or awarded the match is the winner, regardless of the score at retirement.", detail: "Disqualification uses the same first set condition. The Match Winner clause does not specify a different retirement threshold for bets placed during play; any specific bet terms still apply.", source: "https://help.coral.co.uk/en/sports-help/rules/tennis" },
  { name: "Unibet", family: "point", threshold: "First point must be scored", early: "Settles after the first point", own: "Loses", opponent: "Paid as a winner", note: "A completed first set is not required. After the first point is scored, match winner bets settle on the player progressing.", detail: "This is section 27 of the UK sportsbook rules linked from Unibet UK’s current terms, version 1.2a. Do not substitute an older international rulebook. It is the Match Winner clause, not the rules for total games or set betting. Confirm the relevant market terms for a bet placed during play.", source: "https://www.unibet.co.uk/polopoly_fs/1.2812502.1790259752!/menu/standard/file/Unibet%20UK%20KSP%20v1.2a.pdf", sourceLabel: "UK rules PDF · section 27", extraSource: "https://www.unibet.co.uk/general-info/terms" },
  { name: "William Hill", family: "match", threshold: "Match must finish", early: "Both bets refunded", own: "Refund", opponent: "Refund", note: "Match winner bets are void if either player retires. Completing a set does not change that.", detail: "William Hill also voids match bets following a disqualification. These are the UK online tennis rules; check any specific terms attached to the market or promotion.", source: "https://help.williamhill.com/hc/en-gb/articles/28998213514397--Tennis" },
  { name: "Betfred", family: "match", threshold: "Match must finish", early: "Both bets refunded", own: "Refund", opponent: "Refund", note: "A retirement voids match bets even after a completed set. Do not confuse this with its disqualification rule.", detail: "On a disqualification, the defaulted player is treated as the loser and the opponent as the winner. The retirement refund rule is separate. Check specific market terms for any bet placed during play.", source: "https://www.betfred.com/help/bet-rules/tennis" },
  { name: "Betway", family: "match", threshold: "Match must finish", early: "Both bets refunded", own: "Refund", opponent: "Refund", note: "A started but unfinished match voids match bets. A completed first set is not enough.", detail: "Disqualification is an exception: the player awarded the match is the winner. The linked page is Betway’s GB tennis rulebook. Check any market or promotion conditions attached to your bet.", source: "https://betway.com/gb/en/dyn/tennis" },
  { name: "BetMGM UK", family: "match", threshold: "Match must finish", early: "Both bets refunded", own: "Refund", opponent: "Refund", note: "Retirement leaves a match winner bet undecided, so it is void. UK rules are different from other BetMGM jurisdictions.", detail: "Section 19 covers tennis. Default, retirement and walkover void undecided markets. This guide concerns Match Winner only; rules for already determined markets are outside its scope.", source: "https://www.betmgm.co.uk/sport-rules", sourceLabel: "UK rules · section 19" },
  { name: "BoyleSports", family: "match", threshold: "Match must finish", early: "Both bets refunded", own: "Refund", opponent: "Refund", note: "Match bets are void if a match starts but is not completed, regardless of how many sets have finished.", detail: "The tennis section’s Match / Set Betting / Correct Score clause gives the completion requirement. Withdrawal or disqualification before the match starts also voids the bet. Check any specific promotional conditions separately.", source: "https://www.boylesports.com/home/rulebook", sourceLabel: "Rulebook · Tennis" },
  { name: "10bet", family: "match", threshold: "Match must finish", early: "Both bets refunded", own: "Refund", opponent: "Refund", note: "Undecided bets are void after retirement, whatever stage the match has reached.", detail: "The UK tennis rules also void undecided bets after disqualification and walkover. The page covers bets placed before the match and during play.", source: "https://www.10bet.co.uk/tennis" },
  { name: "QuinnBet", family: "match", threshold: "Match must finish", early: "Both bets refunded", own: "Refund", opponent: "Refund", note: "A retirement voids undecided bets. Match Winner is settled at the end of the match, so the stake is returned.", detail: "Both the pre event rules (6.01, 6.07, 6.10) and in play rules (7.01, 7.08, 7.11) confirm this treatment. Default and walkover also void undecided bets.", source: "https://www.quinnbet.com/uk/betting-rules", sourceLabel: "UK rules · sections 6 and 7" },
];
