import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import Footer from '@/components/Footer';
import EditorialIcon from '@/components/EditorialIcon';
import PageHomeLink from '@/components/PageHomeLink';
import FootballAtlasClient from '@/components/football-atlas/FootballAtlasClient';
import { FootballAtlasGuide } from '@/components/football-atlas/FootballAtlasGuide';
import release from '@/data/football-atlas-release.json';
import './football-atlas.css';
export const dynamic = 'force-static';
export const revalidate = false;
const url = 'https://ilmargine.bet/football-atlas';
const title = 'Return Atlas Football: Club ROI & Betting History';
const description = 'Explore football betting returns at Pinnacle prices across the Premier League, Serie A, La Liga, Bundesliga and Ligue 1. Filter seasons, venue, favourites, underdogs and odds ranges.';
export const metadata: Metadata = {
    title, description, alternates: { canonical: url }, robots: { index: true, follow: true },
    openGraph: { title, description, url, type: 'website', images: [{ url: `${url}/share-v1-square.png`, width: 1200, height: 1200, type: 'image/png', alt: 'Return Atlas Football — league club ROI, profit and betting history' }] },
    twitter: { card: 'summary_large_image', title, description, images: [`${url}/share-v1-wide.png`] },
};
export default function FootballAtlasPage() {
    return <div className="min-h-screen bg-[#0f1117] text-slate-100"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'WebApplication', '@id': `${url}#application`, name: 'Return Atlas Football', url, description, applicationCategory: 'SportsApplication', operatingSystem: 'Web', isAccessibleForFree: true, publisher: { '@type': 'Organization', name: 'Il Margine', url: 'https://ilmargine.bet' } }) }} /><main className="football-atlas"><header className="fa-hero page-heading"><div className="fa-utility"><PageHomeLink /><div className="fa-sport-links"><Link href="/return-atlas" prefetch={false}>Tennis</Link><span aria-current="page">Football</span></div></div><p className="fa-eyebrow">The price. The result. The return.</p><h1 className="fa-brand"><span className="sr-only">Return Atlas Football</span><Image src="/football-atlas/wordmark-football-v1.png" alt="" aria-hidden="true" width={2172} height={724} priority unoptimized /></h1><p className="fa-intro">How would backing your club have paid?<br />Explore the returns behind the results, across Europe’s top five domestic leagues.</p><div className="fa-meta"><span>League matches only</span><span>Pinnacle prices</span><span>One unit per bet</span><span>2012/13 onwards</span><a href="#football-method">How it works ↓</a></div><p className="fa-filter-note">Archive checked {release.checkedAt.slice(0, 10)} · Latest priced match {release.through}</p></header>
 <FootballAtlasGuide />
 <FootballAtlasClient indexUrl={release.indexUrl}/>
 <section className="fa-method" id="football-method"><p className="fa-eyebrow">Understand the numbers</p><h2>Three outcomes. Every result counts.</h2><div className="fa-method-grid"><div><EditorialIcon name="markets" className="fa-method-icon"/><h3>Back a team, the draw or its opponent</h3><p>A team-win bet loses if the match is drawn. Back draw uses the actual recorded draw price. All results are settled after 90 minutes plus stoppage time.</p></div><div><EditorialIcon name="compare" className="fa-method-icon"/><h3>Compare like with like</h3><p>Favourite and underdog compare the named team’s win price with its opponent’s. A favourite can be above 2.00. Season, venue and odds filters narrow the same record together.</p></div><div><EditorialIcon name="bankroll" className="fa-method-icon"/><h3>Returns at a constant stake</h3><p>Each bet risks 1u. A win at 2.50 makes 1.50u profit; a loss costs 1u. ROI is total profit divided by stakes. Team W/D/L and betting wins/losses are shown separately.</p></div></div>
 <details><summary>Which matches and prices are included?</summary><p>This archive contains {release.matches.toLocaleString('en-GB')} priced matches among {release.fixtures.toLocaleString('en-GB')} completed league fixtures in the loaded archive. Only Premier League, Serie A, La Liga, Bundesliga and Ligue 1 fixtures are included. Domestic cups, Champions League, Europa League, Conference League and other competitions are excluded, as are incomplete or unresolved prices. Counts describe this archive, not a guarantee of every match ever played.</p><p>Older records use recorded Pinnacle closing prices. Recent archived prices use the last independently checked pre-match quote within 30 minutes of kick-off. The ledger labels each basis. Neither is a guarantee that a price was executable at your stake. Conflicting quotes are excluded; Bet365 is not substituted.</p><p>{release.acquisitionComplete ? 'The current archive acquisition has finished.' : 'Recent-price acquisition is still running; coverage may expand after validation.'} The data check date is separate from the latest match date.</p></details>
 <details><summary>How do the odds ranges work?</summary><p>The odds range always refers to the named team’s win price, even when backing the draw or the opponent. Preset ranges include the lower bound and exclude the upper: 2.50 belongs to 2.50–3.00. Custom ranges include both bounds. Missing odds remain visible in the coverage count before role and odds filtering.</p></details>
 <details><summary>Why are double chance and Asian handicaps not included?</summary><p>They require their own recorded prices. Team −0.5 has the same settlement as a team win, but its quoted price can differ. Team +0.5 wins on a draw as well as a team win. We do not turn 1X2 odds into invented historical double-chance or handicap returns.</p></details>
 <details><summary>What can a high historical ROI tell me?</summary><p>It shows what happened in the selected matches. A small sample, a few large winners or missing prices can dominate the result. Comparing many clubs and filters also makes chance standouts more likely. Use the full ledger, sample size and drawdown alongside ROI; historical leaders are not forecasts or published picks.</p></details>
 <p className="fa-filter-note"><Link href="/faq#return-atlas" prefetch={false}>Return Atlas questions &amp; worked examples →</Link></p><p className="fa-filter-note">The archive check date and latest included match date are shown above. Updates are published after validation; this is not a live odds feed.</p></section></main><Footer /></div>;
}
