import type { Metadata } from "next";
import Link from "next/link";
import ResourceArticlePage from "@/components/ResourceArticlePage";
import TennisRetirementComparison from "@/components/TennisRetirementComparison";
import EditorialIcon from "@/components/EditorialIcon";
import ToolEmblem from "@/components/ToolEmblem";
import { BASE_URL } from "@/lib/config";
import { RETIREMENT_REVIEW_DATE } from "@/lib/tennis-retirement-rules";
import "./retirement.css";

export const dynamic = "force-static";
const path = "/resources/tennis-retirement-rules";
const title = "Tennis Retirement Betting Rules: UK Bookmaker Guide";
const description = "Does a tennis retirement win, lose or void your bet? Compare UK match winner rules at bet365, Sky Bet, Paddy Power, Unibet, Ladbrokes and more.";
export const metadata: Metadata = {
  title: { absolute: `${title} | Il Margine` }, description,
  alternates: { canonical: `${BASE_URL}${path}` }, robots: { index: true, follow: true },
  openGraph: { type: "article", title, description, url: `${BASE_URL}${path}`, siteName: "Il Margine", publishedTime: RETIREMENT_REVIEW_DATE, modifiedTime: RETIREMENT_REVIEW_DATE, images: [{ url: `${BASE_URL}/brand/20260913/social.png`, width: 1200, height: 630, alt: "Il Margine betting research and guides" }] },
  twitter: { card: "summary_large_image", title, description, images: [`${BASE_URL}/brand/20260913/social.png`] },
};
const faq = [
  { q: "Is a tennis bet void if a player retires?", a: "It depends on the bookmaker. Some require the whole match to finish. Others settle after the first completed set or first point. Some pay the opponent as a winner while refunding bets on the retiring player. Use the bookmaker comparison above and check the tournament exceptions." },
  { q: "Does my player need to win a set for the bet to count?", a: "No. A completed first set rule means that either player must have won the first set. It does not mean your selection must win it. A retirement at 5–4 is still inside an unfinished first set; a retirement at 6–4, 0–0 comes after a completed set." },
  { q: "What happens if my player is winning when they retire?", a: "Being ahead does not make a match winner bet a winner. The bookmaker’s retirement rule decides whether your bet loses or is refunded. Your opponent may progress despite trailing on the scoreboard." },
  { q: "What is the difference between a retirement and a walkover?", a: "A retirement happens after play starts. A walkover happens before the match starts. An ordinary match winner bet on an unstarted match is normally void, but tournament outright bets are a different market and are outside this guide." },
  { q: "Are Challenger and ITF retirement rules the same as ATP rules?", a: "Not always. Sky Bet, Paddy Power and Betfair Sportsbook include Challenger in their listed first set protection, but void ITF, UTR and exhibition match bets after retirement at any stage. bet365’s separate retirement promotion excludes Challenger, World Tennis Tour and UTR. Read the competition coverage, not just the headline rule." },
  { q: "Does bet365 pay if my opponent retires?", a: "Its standard Match Betting rule voids a retirement. A separate promotion can award Bet Credits on eligible singles bets placed before play in ATP, WTA and Grand Slam events. Bet Credits are not a normal cash payout. Your own player retiring still voids the bet; check the linked promotion for eligibility and conditions." },
  { q: "Do these rules apply to bets placed during the match?", a: "Do not assume that a promotion covers bets placed during play. bet365’s standard rule explicitly includes them, but its retirement promotion is for bets placed before play. QuinnBet publishes matching completion requirements in its pre event and in play sections. Other entries link the Match Winner rule and flag where no separate in play condition is specified." },
  { q: "Does a disqualification have the same result as retirement?", a: "Not necessarily. bet365, Betfred and Betway distinguish them: the player awarded the match can be the winner after disqualification even though a retirement would void the bet. Read the exceptions under your bookmaker before applying this retirement comparison." },
];

export default function TennisRetirementRulesPage() {
  return <ResourceArticlePage eyebrow="Tennis betting rules · UK" title="A player retires. What happens to your bet?" description="The same unfinished match can mean a win, a loss or a refund. Compare tennis match winner settlement across UK bookmakers before you choose your price." canonicalPath={path} datePublished={RETIREMENT_REVIEW_DATE} dateModified={RETIREMENT_REVIEW_DATE} takeaway="A completed first set does not mean your player has to win that set. And a player advancing to the next round does not guarantee that your bookmaker pays the bet." toc={[{ id: "rule-types", label: "The four rule types" }, { id: "bookmaker-rules", label: "Find your bookmaker" }, { id: "example", label: "A £20 example" }, { id: "before-betting", label: "What to check" }, { id: "questions", label: "Common questions" }]}>
    <section className="guide-section" id="rule-types"><div className="guide-section-heading"><EditorialIcon name="guide" /><h2>Tennis retirement rules, in plain English</h2></div><p>This guide covers UK online bets on <strong>who wins a single tennis match</strong>. It does not cover aces, double faults, handicaps, total games, set betting or tournament winners.</p>
      <div className="retirement-types">
        <div><span className="retirement-type-number">01</span><h3>One point</h3><p>Once the first point is scored, the player progressing wins the match bet. You do not need a completed set.</p></div>
        <div><span className="retirement-type-number">1 SET</span><h3>First set completed</h3><p>Before the set ends, both bets are void. After it ends, the player progressing wins and the retiring player loses.</p></div>
        <div><span className="retirement-type-number">1 SET +</span><h3>First set with a refund</h3><p>After a full set, the opponent is paid as a winner and the retiring player’s bet is refunded. Tournament exceptions matter.</p></div>
        <div><span className="retirement-type-number">FULL</span><h3>Completed match</h3><p>A retirement voids both match bets, even late in the final set. A separate promotion may offer a different benefit.</p></div>
      </div>
    </section>
    <section className="guide-section" id="bookmaker-rules"><div className="guide-section-heading"><EditorialIcon name="compare" /><h2>Compare bookmaker retirement rules</h2></div><p><strong>14 bookmakers checked on 7 October 2026.</strong> These are retirement rules for ordinary cash Match Winner bets. “Refund” means the stake is returned with no profit. Open each entry for its official source and exceptions.</p><TennisRetirementComparison /><p className="retirement-coverage">This is a verified comparison, not a claim to cover every UK operator. Betfair Exchange, betting shops and international versions of these brands are not included. We have not assigned a rule to bookmakers whose current UK terms we could not confirm.</p></section>
    <section className="guide-section" id="example"><div className="guide-section-heading"><EditorialIcon name="bankroll" /><h2>Same £20 bet. Different return.</h2></div><p>You back Player A at 2.50. The first set finishes 6–4, then a player retires in set two. Total return includes your original £20 stake.</p><div className="retirement-example-grid">
      <div><h3>Your player retires</h3><dl><div><dt>Completed match rule</dt><dd>£20 refund</dd></div><div><dt>First set rule</dt><dd>£0</dd></div><div><dt>First set with refund</dt><dd>£20 refund</dd></div><div><dt>First point rule</dt><dd>£0</dd></div></dl></div>
      <div><h3>The opponent retires</h3><dl><div><dt>Completed match rule</dt><dd>£20 refund</dd></div><div><dt>First set rule</dt><dd>£50 return</dd></div><div><dt>First set with refund</dt><dd>£50 return</dd></div><div><dt>First point rule</dt><dd>£50 return</dd></div></dl></div>
    </div><p className="retirement-coverage">Illustration using standard rules in an eligible competition. Promotions, Bet Credits and special bet types are excluded. A £50 return here is £30 profit plus the £20 stake.</p></section>
    <section className="guide-section" id="before-betting"><div className="guide-section-heading"><EditorialIcon name="method" /><h2>Price is only part of the comparison</h2></div><p>Two bookmakers can quote the same player at similar odds but offer different settlement terms. Check these three things together.</p><ol className="guide-checklist"><li><div><strong>The exact market and competition</strong><p>Look for Match Winner, Match Betting or To Win Match. Check whether the event is ATP, WTA, Challenger, ITF, UTR or an exhibition.</p></div></li><li><div><strong>When you placed the bet</strong><p>A bet placed before play and a bet placed during the match may have different promotion eligibility. Use the conditions attached to your bet.</p></div></li><li><div><strong>Cash, refund or Bet Credits</strong><p>A refund returns the original cash stake. A cash win pays the accepted odds. Bet Credits come with separate conditions and are not interchangeable with cash.</p></div></li></ol><p>Rules can change. This page records the conditions checked on the date above; the bookmaker’s applicable terms and your bet receipt determine settlement. Keep both if a result needs querying.</p><div className="guide-actions"><Link href="/bookmakers"><ToolEmblem name="margin" className="tool-emblem--compact" />Compare bookmaker margins ↗</Link><Link href="/tennis-tips"><ToolEmblem name="tennis" className="tool-emblem--compact" />Explore tennis picks ↗</Link></div></section>
    <section className="guide-section" id="questions"><div className="guide-section-heading"><EditorialIcon name="about" /><h2>Tennis retirement betting questions</h2></div><div className="retirement-faq">{faq.map(item => <details key={item.q}><summary>{item.q}<span aria-hidden="true">+</span></summary><p>{item.a}</p></details>)}</div></section>
  </ResourceArticlePage>;
}
