import type { Signal } from "../types";

const sampleSignalsBase: Signal[] = [
  {
    id: "mateta-palace-everton",
    match: "Crystal Palace vs Everton",
    competition: "Premier League",
    kickoff: "Tonight 20:00 UK",
    venue: "Selhurst Park",
    player: "Jean-Philippe Mateta",
    team: "Crystal Palace",
    position: "CF",
    playerNumber: "14",
    teamPrimaryColor: "#1d4ed8",
    teamSecondaryColor: "#b91c1c",
    market: "Anytime goalscorer",
    fairOdds: 2.8,
    bestBookOdds: 3.6,
    bestBookmaker: "Pinnacle",
    marketAverageOdds: 3.42,
    modelProbability: 35.7,
    bookmakerProbability: 27.8,
    projectedMinutes: 86,
    teamExpectedNpxg: 1.62,
    playerRecentNpxg: 0.52,
    attackingShare: 28,
    opponentXga: 1.74,
    fixtureSwing: 18,
    penaltyRole: "Primary",
    lineupStatus: "Projected starter",
    confidence: "High",
    accent: "from-emerald-400 to-lime-300",
    playerMetrics: [
      { label: "Recent chance quality", value: "0.52", percentile: 91 },
      { label: "Share of team chances", value: "28%", percentile: 87 },
      { label: "Projected minutes", value: "86", percentile: 90 },
      { label: "Penalty role", value: "Primary", percentile: 88 },
    ],
    opponentMetrics: [
      { label: "Opponent weakness", value: "1.74", percentile: 78 },
      { label: "Shots conceded", value: "14.2", percentile: 82 },
      { label: "Box touches allowed", value: "31.4", percentile: 76 },
      { label: "Set-piece pressure", value: "0.32", percentile: 69 },
    ],
    edgeReasons: [
      "Model prices the scoring chance 7.9pp higher than the best book.",
      "Strong share of team attacking output over recent starts.",
      "Penalty role materially lifts the floor if he starts.",
      "Opponent profile allows above-average central box volume.",
    ],
  },
  {
    id: "watkins-villa-wolves",
    match: "Aston Villa vs Wolves",
    competition: "Premier League",
    kickoff: "Sat 15:00 UK",
    venue: "Villa Park",
    player: "Ollie Watkins",
    team: "Aston Villa",
    position: "CF",
    playerNumber: "11",
    teamPrimaryColor: "#7f1d1d",
    teamSecondaryColor: "#38bdf8",
    market: "Anytime goalscorer",
    fairOdds: 2.34,
    bestBookOdds: 2.85,
    bestBookmaker: "bet365",
    marketAverageOdds: 2.72,
    modelProbability: 42.7,
    bookmakerProbability: 35.1,
    projectedMinutes: 88,
    teamExpectedNpxg: 1.88,
    playerRecentNpxg: 0.49,
    attackingShare: 26,
    opponentXga: 1.61,
    fixtureSwing: 14,
    penaltyRole: "Secondary",
    lineupStatus: "Likely starter",
    confidence: "High",
    accent: "from-sky-400 to-emerald-300",
    playerMetrics: [
      { label: "Recent chance quality", value: "0.49", percentile: 88 },
      { label: "Share of team chances", value: "26%", percentile: 82 },
      { label: "Projected minutes", value: "88", percentile: 92 },
      { label: "Penalty role", value: "Backup", percentile: 58 },
    ],
    opponentMetrics: [
      { label: "Opponent weakness", value: "1.61", percentile: 72 },
      { label: "Shots conceded", value: "13.8", percentile: 74 },
      { label: "Box touches allowed", value: "29.7", percentile: 71 },
      { label: "Set-piece pressure", value: "0.24", percentile: 55 },
    ],
    edgeReasons: [
      "Minutes projection is stable and keeps his anytime probability high.",
      "Recent open-play chance volume is above market expectation.",
      "Home attacking environment supports multiple Villa goal paths.",
    ],
  },
  {
    id: "isak-newcastle-west-ham",
    match: "Newcastle vs West Ham",
    competition: "Premier League",
    kickoff: "Sat 17:30 UK",
    venue: "St James' Park",
    player: "Alexander Isak",
    team: "Newcastle",
    position: "CF",
    playerNumber: "14",
    teamPrimaryColor: "#0f172a",
    teamSecondaryColor: "#f8fafc",
    market: "Anytime goalscorer",
    fairOdds: 2.12,
    bestBookOdds: 2.54,
    bestBookmaker: "Pinnacle",
    marketAverageOdds: 2.43,
    modelProbability: 47.2,
    bookmakerProbability: 39.4,
    projectedMinutes: 82,
    teamExpectedNpxg: 2.04,
    playerRecentNpxg: 0.61,
    attackingShare: 30,
    opponentXga: 1.68,
    fixtureSwing: 22,
    penaltyRole: "Primary",
    lineupStatus: "Projected starter",
    confidence: "Medium",
    accent: "from-cyan-400 to-emerald-300",
    playerMetrics: [
      { label: "Recent chance quality", value: "0.61", percentile: 95 },
      { label: "Share of team chances", value: "30%", percentile: 92 },
      { label: "Projected minutes", value: "82", percentile: 76 },
      { label: "Penalty role", value: "Primary", percentile: 88 },
    ],
    opponentMetrics: [
      { label: "Opponent weakness", value: "1.68", percentile: 75 },
      { label: "Shots conceded", value: "15.1", percentile: 86 },
      { label: "Box touches allowed", value: "34.0", percentile: 84 },
      { label: "Set-piece pressure", value: "0.21", percentile: 49 },
    ],
    edgeReasons: [
      "High individual share meets a high team expected-goals projection.",
      "Market average sits materially above the model fair price.",
      "Opponent concedes volume in the zones he attacks most.",
    ],
  },
  {
    id: "david-lille-lens",
    match: "Lille vs Lens",
    competition: "Ligue 1",
    kickoff: "Sun 19:45 UK",
    venue: "Decathlon Arena",
    player: "Jonathan David",
    team: "Lille",
    position: "ST",
    playerNumber: "9",
    teamPrimaryColor: "#dc2626",
    teamSecondaryColor: "#1e3a8a",
    market: "Anytime goalscorer",
    fairOdds: 2.55,
    bestBookOdds: 3.05,
    bestBookmaker: "Betfair Sportsbook",
    marketAverageOdds: 2.94,
    modelProbability: 39.2,
    bookmakerProbability: 32.8,
    projectedMinutes: 87,
    teamExpectedNpxg: 1.54,
    playerRecentNpxg: 0.46,
    attackingShare: 30,
    opponentXga: 1.42,
    fixtureSwing: 10,
    penaltyRole: "Primary",
    lineupStatus: "Projected starter",
    confidence: "Medium",
    accent: "from-red-400 to-amber-300",
    playerMetrics: [
      { label: "Recent chance quality", value: "0.46", percentile: 84 },
      { label: "Share of team chances", value: "30%", percentile: 91 },
      { label: "Projected minutes", value: "87", percentile: 91 },
      { label: "Penalty role", value: "Primary", percentile: 88 },
    ],
    opponentMetrics: [
      { label: "Opponent weakness", value: "1.42", percentile: 59 },
      { label: "Shots conceded", value: "12.7", percentile: 61 },
      { label: "Box touches allowed", value: "27.1", percentile: 62 },
      { label: "Set-piece pressure", value: "0.27", percentile: 60 },
    ],
    edgeReasons: [
      "Penalty role and minutes security keep him above the market curve.",
      "Player share is stronger than the fixture-level price suggests.",
      "Market average is still too long after removing the outlier price.",
    ],
  },
  {
    id: "vlahovic-juve-torino",
    match: "Juventus vs Torino",
    competition: "Serie A",
    kickoff: "Sun 17:00 UK",
    venue: "Allianz Stadium",
    player: "Dusan Vlahovic",
    team: "Juventus",
    position: "CF",
    playerNumber: "9",
    teamPrimaryColor: "#111827",
    teamSecondaryColor: "#f8fafc",
    market: "Anytime goalscorer",
    fairOdds: 2.66,
    bestBookOdds: 3.2,
    bestBookmaker: "Spreadex",
    marketAverageOdds: 3.02,
    modelProbability: 37.6,
    bookmakerProbability: 31.3,
    projectedMinutes: 78,
    teamExpectedNpxg: 1.49,
    playerRecentNpxg: 0.43,
    attackingShare: 29,
    opponentXga: 1.51,
    fixtureSwing: 12,
    penaltyRole: "Primary",
    lineupStatus: "Projected starter",
    confidence: "Medium",
    accent: "from-zinc-200 to-emerald-300",
    playerMetrics: [
      { label: "Recent chance quality", value: "0.43", percentile: 79 },
      { label: "Share of team chances", value: "29%", percentile: 88 },
      { label: "Projected minutes", value: "78", percentile: 68 },
      { label: "Penalty role", value: "Primary", percentile: 88 },
    ],
    opponentMetrics: [
      { label: "Opponent weakness", value: "1.51", percentile: 66 },
      { label: "Shots conceded", value: "13.1", percentile: 64 },
      { label: "Box touches allowed", value: "28.8", percentile: 69 },
      { label: "Set-piece pressure", value: "0.34", percentile: 74 },
    ],
    edgeReasons: [
      "Market is slow to price his central shot share in this setup.",
      "Penalty role protects the scoring probability if game state is tight.",
      "Opponent set-piece profile adds a second scoring route.",
    ],
  },
];

function publicTierFromPercentile(
  percentile: number | undefined,
  high = "Strong",
  good = "Good",
  average = "Average",
  low = "Limited",
) {
  if (percentile === undefined) return "Unknown";
  if (percentile >= 75) return high;
  if (percentile >= 55) return good;
  if (percentile >= 35) return average;
  return low;
}

function publicizeSignal(signal: Signal): Signal {
  const recentPercentile = signal.playerMetrics[0]?.percentile;
  const sharePercentile = signal.playerMetrics[1]?.percentile;
  const minutesPercentile = signal.playerMetrics[2]?.percentile;
  const penaltyPercentile = signal.playerMetrics[3]?.percentile;
  const opponentPercentile = signal.opponentMetrics[0]?.percentile;
  const teamTier = signal.teamExpectedNpxg && signal.teamExpectedNpxg >= 1.75 ? "Strong" : signal.teamExpectedNpxg && signal.teamExpectedNpxg >= 1.35 ? "Positive" : "Average";
  const opponentTier = signal.opponentXga && signal.opponentXga >= 1.65 ? "High" : signal.opponentXga && signal.opponentXga >= 1.4 ? "Positive" : "Average";

  return {
    ...signal,
    recentChanceQuality:
      signal.recentChanceQuality ??
      publicTierFromPercentile(recentPercentile, "Strong", "Good", "Average", "Limited"),
    teamAttackingOutlook: signal.teamAttackingOutlook ?? teamTier,
    opponentDefensiveWeakness: signal.opponentDefensiveWeakness ?? opponentTier,
    playerMetrics: [
      {
        label: "Recent chance quality",
        value: signal.recentChanceQuality ?? publicTierFromPercentile(recentPercentile, "Strong", "Good", "Average", "Limited"),
        percentile: recentPercentile,
        note: "Recent non-penalty chance volume",
      },
      {
        label: "Share of team chances",
        value: `${signal.attackingShare}%`,
        percentile: sharePercentile,
        note: "How much of the team threat runs through him",
      },
      {
        label: "Lineup confidence",
        value: signal.lineupStatus,
        percentile: minutesPercentile,
      },
      {
        label: "Penalty role",
        value: signal.penaltyRole,
        percentile: penaltyPercentile,
      },
    ],
    opponentMetrics: [
      {
        label: "Team attacking outlook",
        value: signal.teamAttackingOutlook ?? teamTier,
        percentile: signal.opponentMetrics[1]?.percentile ?? signal.playerMetrics[1]?.percentile,
      },
      {
        label: "Opponent defensive weakness",
        value: signal.opponentDefensiveWeakness ?? opponentTier,
        percentile: opponentPercentile,
      },
      {
        label: "Fixture boost",
        value: `${signal.fixtureSwing >= 0 ? "+" : ""}${signal.fixtureSwing}%`,
        percentile: signal.opponentMetrics[2]?.percentile,
      },
      {
        label: "Projected minutes",
        value: signal.projectedMinutes ? `${signal.projectedMinutes} min` : signal.lineupStatus,
        percentile: minutesPercentile,
      },
    ],
  };
}

export const sampleSignals = sampleSignalsBase.map(publicizeSignal);
