import Link from "next/link";
import ResourceArticlePage from "@/components/ResourceArticlePage";
import GuideBlocks from "@/components/GuideBlocks";
import RogerGuideActions from "@/components/RogerGuideActions";
import "@/components/resource-library.css";
export default function RogerPage() {
  return <ResourceArticlePage eyebrow="Tennis research assistant" title="Ask Roger a better tennis question" description="Get more useful answers by naming the player, surface and period. Roger helps explore tennis statistics; the numbers still need context and checking." canonicalPath="/resources/roger" dateModified="2026-09-23" icon="about" takeaway="Ask a question the data can answer. A head-to-head record is a description of past matches, not the probability of the next result." toc={[{id:"ask",label:"Start a conversation"},{id:"specific",label:"Make the question specific"},{id:"check",label:"Check the answer"},{id:"tools",label:"Choose the right tool"}]}>
    <section id="ask" className="guide-section"><h2>Start with a player and a question</h2><p>Roger can help with ATP head-to-head results, tournament history and serve or return statistics. Ask for the surface, dates and match count that support the answer. Availability depends on the records held, and usage limits may apply.</p><RogerGuideActions /></section>
    <GuideBlocks sections={[{id:"specific",title:"Make the question specific",table:{caption:"Replace a vague question with a checkable one",headings:["Instead of","Try asking"],rows:[["Is this player good on clay?","What is their clay match record, and over which seasons?"],["Who wins this match?","What is their head-to-head on this surface, and how many meetings is that?"],["Is this court fast?","Which serve or pace measure are you using, for what year?"]]},paragraphs:["A serve-based pace estimate is not necessarily an official Court Pace Index measurement. Ask how the number is defined before comparing two venues."]},{id:"check",title:"Read the answer with the sample attached",steps:[["Check the player and event","Similar names and tournament name changes can produce the wrong match. Include both player names when asking about a fixture."],["Check the period and surface","An all-career statistic and a current-season statistic answer different questions. Ask which one you are seeing."],["Check the count","A 75% win rate could mean three wins from four matches. The denominator matters."],["Check any price separately","A chatbot answer can be incomplete, outdated or mistaken. Use a current market for prices and the published selections page for the official tips."]],note:"Do not include passwords, account details or sensitive personal information. Questions are processed by an AI service to generate the answer."},{id:"tools",title:"Use the right tool for the job",paragraphs:["Return Atlas is the dedicated place to browse player ROI by season, surface and favourite or underdog status, with a visible match history. Roger is useful for asking a narrower statistics question and following it up.","If an answer looks wrong, send the question and the page or match concerned through Contact. A correction is more useful than treating confident wording as proof."]}]} />
    <div className="guide-actions"><Link href="/return-atlas">Open Return Atlas ↗</Link><Link href="/tennis-tips">Published tennis tips ↗</Link><Link href="/contact">Report an issue ↗</Link></div>
  </ResourceArticlePage>;
}
